<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Hassans-MBP" failures="1" tests="1" name="TestRunner" time="8.039" errors="0" timestamp="2024-05-02T20:49:29 EDT" skipped="0">
  <testcase classname="TestRunner" name="runScenario" time="8.039">
    <failure message="expected [Student Information - Fail] but found [Student Information]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Student Information - Fail] but found [Student Information]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at stepDef.Login_steps.studentShouldBeSuccessfullyLoginButFailingOnPurpose(Login_steps.java:66)
at âœ½.student should be successfully login but failing on purpose(file:///Users/hbhuiyan/Documents/TalentTEK/GitStuff/CucumberOnline3x_March24/src/test/java/features/login.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestRunner -->
